jobs:
- name: set-self
  plan:
  - get: src
    trigger: true
  - set_pipeline: defectdojo-boshrelease
    file: src/ci/pipeline.yml
    # var_files:
    #   - src/ci/config.yml

- name: get-blobs
  plan:
    - get: release
      params:
        include_source_tarball: true
      # trigger: true. todo: add this once finished.

    - get: src
      trigger: true
      passed: [set-self]

    - task: process-release # convert from .tar.gz to whatever bosh wants
      file: src/ci/process-release.yml


    # - put: upload-blob

    # - task: commit-and-push-changes

    # - put: create-pull-request

resources:
- name: release
  type: github-release
  source:
    owner: DefectDojo
    repository: django-DefectDojo
    # access_token: ((cg-ci-bot-ghtoken))

- name: src
  type: git
  source:
    uri: https://github.com/cloud-gov/defectdojo-boshrelease
    branch: pipeline
    commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
- name: github-release
  type: registry-image
  source:
    repository: concourse/github-release-resource
