jobs:
- name: set-self
  plan:
  - get: src
    trigger: true
  - set_pipeline: defectdojo-boshrelease
    file: src/ci/pipeline.yml
    # var_files:
    #   - src/ci/config.yml

- name: update-blobs
  plan:
    - in_parallel:
      - get: general-task

      - get: release
        params:
          include_source_tarball: true
        # trigger: true. todo: add this once finished.

      - get: src
        trigger: true
        passed: [set-self]

    - task: process-release
      image: general-task
      file: src/ci/process-release.yml
      params:
        GH_TOKEN: ((cg-ci-bot-ghtoken))

    # - put: upload-blob

    # - task: commit-and-push-changes

    # - put: create-pull-request

resources:
- name: general-task
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

- name: release
  type: github-release
  source:
    owner: DefectDojo
    repository: django-DefectDojo
    access_token: ((cg-ci-bot-ghtoken))

- name: src
  type: git
  source:
    uri: https://github.com/cloud-gov/defectdojo-boshrelease
    branch: pipeline
    commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: github-release
  type: registry-image
  source:
    repository: concourse/github-release-resource
